remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Stronghold of Knowledge
google_analytics: UA-174896496-1
show_downloads: true
url: https://zachdoll.com
    # resume_url: /downloads/zach_doll.pdf
github: 
    twitter_url: https://twitter.com/elanmoridin
    linkedin_url: https://www.linkedin.com/in/zachdoll/
    github_profile: https://github.com/elanmoridin
    resume_url: https://zachdoll.com/downloads/zach_doll.pdf
    