theme: jekyll-theme-hacker
title: Stronghold of Knowledge
google_analytics: UA-174896496-1
show_downloads: true
url: https://zachdoll.com
github: 
    twitter_url: https://twitter.com/elanmoridin
    linkedin_url: https://www.linkedin.com/in/zachdoll/
    github_profile: https://github.com/elanmoridin
    # resume_url: /docs/downloads/zach_doll.pdf